#!/usr/bin/env bash

BUILDPACK_HOME="${BUILDPACK_HOME:-$(pwd)}"

test_is_spring_boot() {
  createPom "
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
</dependency>
"
  capture is_spring_boot "$BUILD_DIR"
  assertCapturedSuccess
}

test_is_spring_boot_fail() {
  createPom "$(withDependency)"
  capture is_spring_boot "$BUILD_DIR"
  # shellcheck disable=SC2119
  assertCapturedError
}

test_is_wildfly_swarm() {
  createPom "
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>bom</artifactId>
</dependency>
"
  capture is_wildfly_swarm "$BUILD_DIR"
  assertCapturedSuccess
}

test_is_wildfly_swarm_fail() {
  createPom "$(withDependency)"
  capture is_wildfly_swarm "$BUILD_DIR"
  # shellcheck disable=SC2119
  assertCapturedError
}

test_has_postgres() {
  createPom "
<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
</dependency>
"
  capture has_postgres "$BUILD_DIR"
  assertCapturedSuccess
}

test_has_postgres_fail() {
  createPom "$(withDependency)"
  capture has_postgres "$BUILD_DIR"
  # shellcheck disable=SC2119
  assertCapturedError
}

# the modules to be tested
# shellcheck source=lib/common.sh
source "${BUILDPACK_HOME}/lib/common.sh"
# shellcheck source=lib/maven.sh
source "${BUILDPACK_HOME}/lib/maven.sh"
# shellcheck source=lib/frameworks.sh
source "${BUILDPACK_HOME}/lib/frameworks.sh"

# testing utils
# shellcheck source=test/utils
source "${BUILDPACK_HOME}/test/utils"
# shellcheck source=test/helpers.sh
source "${BUILDPACK_HOME}/test/helpers.sh"
# shellcheck source=test/stdlib_stubs.sh
source "${BUILDPACK_HOME}/test/stdlib_stubs.sh"

# import the testing framework
# shellcheck source=test/shunit2
source "${BUILDPACK_HOME}/test/shunit2"
