name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  hatchet:
    name: "Hatchet (${{ matrix.stack }})"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        stack: ["heroku-20", "heroku-22", "heroku-24"]
    env:
      HATCHET_APP_LIMIT: 100
      PARALLEL_SPLIT_TEST_PROCESSES: 8
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_API_USER: ${{ secrets.HEROKU_API_USER }}
      HEROKU_DISABLE_AUTOUPDATE: 1
      HATCHET_BUILDPACK_BASE: https://github.com/heroku/heroku-buildpack-java
      HATCHET_DEFAULT_STACK: ${{ matrix.stack }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Hatchet setup
        run: bundle exec hatchet ci:setup
      - name: Run Hatchet integration tests
        run: bundle exec parallel_split_test test/spec/
